### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by echocbx** [Jin-Yuhan/hexo-theme-anemo#1]
![image](https://user-images.githubusercontent.com/110729988/200748638-327f9be3-2ff2-4e92-a5b8-2ce40322f71c.png)

**Comment by Jin-Yuhan** [comment]
我并没有将这个主题发布到 npm。另外，我不建议您使用这个主题，因为我不一定会持续维护它（

**Comment by echocbx** [comment]
> 我并没有将这个主题发布到 npm。另外，我不建议您使用这个主题，因为我不一定会持续维护它（

球球大佬，能不能先开放下载，哪怕是github，我想参 加 内 测（doge） 
不持续维护没关系，我现在用的主题作者已经一年不维护了。

**Comment by echocbx** [comment]
> 我并没有将这个主题发布到 npm。另外，我不建议您使用这个主题，因为我不一定会持续维护它（

现在我把这个仓库git clone下来之后用这个主题会报错

**Comment by echocbx** [comment]
![图片](https://user-images.githubusercontent.com/110729988/204978462-323d7d90-f112-47a1-afd5-1a7aa0548428.png)
已成功使用（大佬介意的话就不用了
