### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by pk5ls20** [Jin-Yuhan/hexo-theme-anemo#5]
作者好！看到了您的主题hexo-theme-anemo后，对其中的H1/H2标题下划线高亮部分感兴趣，查阅一番后发现主题在渲染h1标题和h2标题时会加入<span>标签，请问这样实现加入<span>的原理是什么呢，非常感谢！

**Comment by Jin-Yuhan** [comment]
其实是网页加载完以后动态加的。 [>>>代码传送门<<<](https://github.com/Jin-Yuhan/hexo-theme-anemo/blob/dc938c50bf7d649a75699d6ffbe7fcbaf823c68c/source/_ts/anemo/components/markdownBeautifier.ts#L9)

**Comment by pk5ls20** [comment]
> 其实是网页加载完以后动态加的。 [>>>代码传送门<<<](https://github.com/Jin-Yuhan/hexo-theme-anemo/blob/dc938c50bf7d649a75699d6ffbe7fcbaf823c68c/source/_ts/anemo/components/markdownBeautifier.ts#L9)

感谢，但还想问一下这个ts文件是如何引入并使用的，查阅一番资料后还是不得其解...

**Comment by Jin-Yuhan** [comment]
ts 代码写完以后，用 tsc 编译成 [main.min.js](https://github.com/Jin-Yuhan/hexo-theme-anemo/blob/dc938c50bf7d649a75699d6ffbe7fcbaf823c68c/source/js/main.min.js)，然后在 [这里](https://github.com/Jin-Yuhan/hexo-theme-anemo/blob/dc938c50bf7d649a75699d6ffbe7fcbaf823c68c/layout/_partial/scripts.ejs#L4) 引入。

**Comment by pk5ls20** [comment]
问题已解决，感谢🥰
